theme: jekyll-theme-midnight

# Site settings
title: Personal Website of Justin Morrow
email: justin@morrow.gdn
description: > # this means to ignore newlines until "baseurl:"
  I don't sit back and let the world happen to me, I go out and happen to the world.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://justinpmorrow.com" # the base hostname & protocol for your site
github_username:  justinmorrow
